# Generated by Django 3.0.4 on 2020-04-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('codechef', models.IntegerField(default=0)),
                ('codeforces', models.IntegerField(default=0)),
                ('hackerearth', models.IntegerField(default=0)),
                ('hackerrank', models.IntegerField(default=0)),
                ('spoj', models.IntegerField(default=0)),
                ('password', models.CharField(max_length=30)),
                ('no', models.CharField(default='u', max_length=10)),
            ],
        ),
    ]
